import { useRouter } from "next/router";
import Head from "next/head";
import Level from "../../components/level";
import levels from "../../data/levelsData";

export default function StagePage() {
  const router = useRouter();
  const { stage } = router.query;

  // 查找對應的 stage
  const levelData = levels.find((level) => level.stage === Number(stage));
  console.log(levelData);

  // 在 levelData 還未加載時返回 null 或顯示加載指示器
  if (!levelData) {
    return <p>加載中...</p>;
  }

  return (
    <>
      <Head>
        <title>Level {levelData.stage}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Level level={levelData.stage} />
    </>
  );
}
