import { useRouter } from "next/router";
import Head from "next/head";
import levels from "../../data/levelsData";
import styles from "../../styles/camera.module.css";
import Image from "next/image";
import Button from "../../components/button";
import BackButton from "../../components/btn-back";
import React, { useState, useRef } from "react";
import Webcam from "react-webcam";
import Link from "next/link";

export default function StagePage() {
  const router = useRouter();
  const { camera } = router.query;
  const webcamRef = useRef(null);
  const [capturedImage, setCapturedImage] = useState(null);

  // 查找對應的 stage
  const levelData = levels.find((level) => level.stage === Number(camera));
  // console.log(levelData);

  if (!levelData) {
    return <p>加載中...</p>;
  }

  const videoConstraints = {
    width: 375,
    height: 667,
    facingMode: "user",
  };

  const capture = () => {
    const imageSrc = webcamRef.current.getScreenshot();
    setCapturedImage(imageSrc);
    console.log(imageSrc);
  };

  const takeAgain = () => {
    setCapturedImage(null);
  };

  return (
    <>
      <Head>
        <title>Camera{levelData.stage}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {/* 主要內容 */}
        <div>
          {/* 相機 */}
          {/* capturedImage 為空的時候 */}
          {!capturedImage && (
            <Webcam
              audio={false}
              ref={webcamRef}
              screenshotFormat="image/jpeg"
              className={styles.webcam}
              videoConstraints={videoConstraints}
            />
          )}
          {/* 裝飾 */}
          <div className={styles.title}>動物同學會</div>
          <Image
            src={`${levelData.backgroundImage}`}
            alt="deco"
            width={120}
            height={120}
            className={styles.deco}
          ></Image>
          {/* 按鍵 */}
          <div className={styles.button_container}>
            {!capturedImage ? (
              <Button onClick={capture}>拍攝</Button>
            ) : (
              <>
                <Button onClick={takeAgain}>再拍一次</Button>
                <Link href="/main">
                  <Button>OK!</Button>
                </Link>
              </>
            )}
          </div>
        </div>

        {/* 展示相片 */}
        {capturedImage && (
          <div className={styles.captured_image_container}>
            <Image
              src={capturedImage}
              alt="CapturedImage"
              width={375}
              height={667}
            />
          </div>
        )}

        {/* 返回鍵 */}
        <BackButton to="/main" className={styles.back_button} />
      </div>
    </>
  );
}
