import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Level from "../../components/level";
import levels from "../../data/levelsData";
import styles from "../../styles/camera.module.css";
import Webcam from "react-webcam";
import Image from "next/image";
import Button from "../../components/button";
import BackButton from "../../components/btn-back";
import { useRef } from "react";
import { useState } from "react";

export default function StagePage() {
  const router = useRouter();
  const { stage } = router.query;
  const webcamRef = useRef(null);
  const [capturedImage, setCapturedImage] = useState(null);

  // 查找對應的 stage
  const levelData = levels.find((level) => level.stage === Number(stage));
  // console.log(levelData);

  // 在 levelData 還未加載時返回 null 或顯示加載指示器
  if (!levelData) {
    return <p>加載中...</p>;
  }

  const videoConstraints = {
    width: 375,
    height: 667,
    facingMode: "user",
  };

  const capture = () => {
    const imageSrc = webcamRef.current.getScreenshot();
    setCapturedImage(imageSrc);
    console.log(imageSrc);
  };

  return (
    <>
      <Head>
        <title>Camera{levelData.stage}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {/* 相機 */}
        <Webcam
          audio={false}
          ref={webcamRef}
          screenshotFormat="image/jpeg"
          className={styles.webcam}
          videoConstraints={videoConstraints}
        />

        {/* 裝飾 */}
        <Image
          src={`${levelData.backgroundImage}`}
          alt="filter"
          width={120}
          height={120}
          className={styles.filter}
        ></Image>

        {/* 按鍵 */}
        <div className={styles.button_container}>
          <Button onClick={capture}>拍攝</Button>
        </div>
        <div className={styles.title}>動物同學會</div>
        <div className={styles.back_button}>
          <BackButton to="/main" className={styles.back_button} />
        </div>

        {/* 展示相片 */}
        {capturedImage && (
          <div className={styles.captured_image_container}>
            <Image
              src={capturedImage}
              alt="CapturedImage"
              width={375}
              height={667}
            />
          </div>
        )}
      </div>
    </>
  );
}
