import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import styles from "../styles/home.module.css";

import Button from "@/components/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.logo}>動物園</div>
        <div className={styles.title}>動物同學會</div>
        <div className={styles.button_container}>
          <Link href="/nickname">
            <Button>開始遊戲</Button>
          </Link>
        </div>
      </div>
    </>
  );
}
