import Head from "next/head";
import Link from "next/link";
import styles from "../styles/home.module.css";
import Button from "../components/button";

export default function Intro1() {
  return (
    <>
      <Head>
        <title>Intro2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.wrapper}>
          <div className={styles.subtitle}>STORY</div>
          <p className={styles.paragraph}>
            今天是動物學院的開學。
            <br />
            第一天，班上的好朋友<span className={styles.text_bold}>小山</span>、
            <span className={styles.text_bold}>小獺</span>、
            <span className={styles.text_bold}>小猩</span>和
            <span className={styles.text_bold}>小貘</span>
            卻都沒來上學，他們發生了什麼事情呢？雲豹老師很擔心，希望我們去他們的家看看。
          </p>
          <div className={styles.button_container}>
            <Link href="/main">
              <Button>GO!</Button>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
