import Head from "next/head";
import Level from "../components/level";

export default function level1() {
  return (
    <>
      <Head>
        <title>Level 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Level level="level1"></Level>
    </>
  );
}
