import { useState } from "react";
import Head from "next/head";
import styles from "../styles/level.module.css";
import Image from "next/image";
import Button from "@/components/button";
import Link from "next/link";
const answers = {
  level1: "正確答案1",
  level2: "正確答案2",
  level3: "正確答案3",
  level4: "正確答案4",
};

export default function level() {
  const [answer, setAnswer] = useState("");
  const [failModal, setFailModal] = useState(false);

  return (
    <>
      <Head>
        <title>Level</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.card}>
          <div className={styles.hint_container}>
            <Link href="/hint1">
              <span className={styles.hint}>提示一</span>
            </Link>
            <Link href="/hint2">
              <span className={styles.hint}>提示二</span>
            </Link>
            <Link href="/hint3">
              <span className={styles.hint}>提示三</span>
            </Link>
          </div>
          <div className={styles.bg_circle}>
            <Image src="/img_animal1.png" width={50} height={50}></Image>
          </div>
          <p className={styles.card_title}>穿山甲</p>
          <p className={styles.card_paragraph}>
            看來要先把中藥舖動物製的中藥材下架抹除，才能找出吸引小山走出迷宮的方式了。
          </p>
          <div className={styles.guide}>先去找找中藥舖的看板在哪裡吧！</div>
          <div className={styles.input_btn_wrapper}>
            <input type="text" placeholder="請在此輸入答案" />
            <Button href="/" onClick={handleCheckAnswer}>
              GO!
            </Button>
          </div>
        </div>
      </div>
    </>
  );
}
