import Head from "next/head";
import styles from "../styles/home.module.css";
import AnimalCard from "../components/card-animal";
import levels from "../data/levelsData";
import { useState, useEffect } from "react";
import BackButton from "../components/btn-back";

export default function Main() {
  const [animals, setAnimals] = useState([]);

  // 從 local storage 中取得關卡狀態，並更新 animals 資料
  useEffect(() => {
    // 取得 local storage 中的資料
    const savedLevels = JSON.parse(localStorage.getItem("levels")) || {};
    // 更新 animals 資料
    const updatedAnimals = levels.map((level) => ({
      ...level,
      isLocked: savedLevels[level.stage]?.isLocked ?? true,
    }));

    setAnimals(updatedAnimals);
    // console.log(updatedAnimals);
  }, []);

  if (!animals) {
    // 在 animals 未定義之前顯示
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* 按鈕們 */}
      <BackButton to="/intro2" />
      <div className={styles.container}>
        {/* 台灣動物區 */}
        <div className={styles.card_container_bg}>
          <div className={styles.main_title}>台灣動物區</div>
          <div className={styles.animal_wrapper}>
            {animals &&
              animals
                .filter((animal) => animal.group === "A")
                .map((animal) => (
                  <AnimalCard key={animal.stage} animal={animal} />
                ))}
          </div>
        </div>
        {/* 熱帶雨林區 */}
        <div className={styles.card_container_bg}>
          <div className={styles.main_title}>熱帶雨林區</div>
          <div className={styles.animal_wrapper}>
            {animals &&
              animals
                .filter((animal) => animal.group === "B")
                .map((animal) => (
                  <AnimalCard key={animal.stage} animal={animal} />
                ))}
          </div>
        </div>
      </div>
    </>
  );
}
