import Head from "next/head";
import Link from "next/link";
import styles from "../styles/home.module.css";
import AnimalCard from "@/components/animal_card";
import levels from "../data/levels";

export default function Main() {
  console.log("data:", levels);
  const animals = Object.values(levels);
  console.log(animals);

  return (
    <>
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {/* 台灣動物區 */}
        <div className={styles.card_container_bg}>
          <div className={styles.main_title}>台灣動物區</div>
          <div className={styles.animal_wrapper}>
            {animals
              .filter((animal) => animal.group === "A")
              .map((animal, index) => (
                <AnimalCard key={index} animal={animal} />
              ))}
          </div>
        </div>
        {/* 熱帶雨林區 */}
        <div className={styles.card_container_bg}>
          <div className={styles.main_title}>熱帶雨林區</div>
          <div className={styles.animal_wrapper}>
            {animals
              .filter((animal) => animal.group === "B")
              .map((animal, index) => (
                <AnimalCard key={index} animal={animal} />
              ))}
          </div>
        </div>
      </div>
      <button className={styles.button_music}></button>
      <button>幫助</button>
      <Link href="/main">
        <button>返回</button>
      </Link>
      <div>Modal</div>
    </>
  );
}
