import Head from "next/head";
import styles from "../styles/home.module.css";
import Button from "../components/button";
import Image from "next/image";
import { useState } from "react";
import Link from "next/link";

export default function Nickname() {
  // 暱稱狀態
  const [nickname, setNickname] = useState("");
  // checkbox狀態
  const [isChecked, setIsChecked] = useState(false);
  const [error, setError] = useState("");

  const handleCheckboxChange = (e) => {
    setIsChecked(e.target.checked);
    if (e.target.checked) {
      setError(""); // 清除錯誤訊息
    }
  };

  // 提交檢查、setItem
  const handleGoClick = (e) => {
    if (nickname.trim() === "") {
      e.preventDefault();
      setError("請輸入遊戲暱稱");
      return;
    }
    if (!isChecked) {
      e.preventDefault();
      setError("您尚未同意使用者條款與隱私權政策");
      return;
    }

    localStorage.setItem("nickname", nickname);
  };

  return (
    <>
      <Head>
        <title>Nickname</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.container_circle}>
          {/* decoration */}
          <div className={styles.stars}>
            <div className={styles.stars_sm}>
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
            </div>
            <Image src="/img_star_lg.svg" alt="star" width={50} height={50} />
            <div className={styles.stars_sm}>
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
            </div>
          </div>

          {/* input */}
          <div className={styles.input_wrapper}>
            <label htmlFor="nickname" className={styles.nickname_label}>
              取一個超酷的遊戲暱稱吧!
            </label>
            <input
              type="text"
              name="nickname"
              id="nickname"
              placeholder="請輸入遊戲暱稱"
              value={nickname}
              onChange={(e) => setNickname(e.target.value)}
            />
          </div>

          {/* checkbox */}
          <div className={styles.checkbox_container}>
            <div className={styles.checkbox_wrapper}>
              <input
                type="checkbox"
                id="toggleIsChecked"
                onClick={handleCheckboxChange}
              />
              您同意<span className={styles.term}>使用者條款</span>與
              <span className={styles.term}>隱私權政策</span>
            </div>
            <p className={styles.alert}>{error}</p>
          </div>

          {/* button */}
          <div className={styles.button_container}>
            <Link href="/intro1">
              <Button onClick={handleGoClick}>GO!</Button>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
