import Head from "next/head";
import styles from "../styles/home.module.css";
import Button from "../components/button";
import Image from "next/image";
import { useState } from "react";
import Link from "next/link";

export default function Nickname() {
  // 暱稱狀態
  const [nickname, setNickname] = useState("");
  // 提交、setItem
  const handleGoClick = (e) => {
    if (nickname.trim() === "") {
      e.preventDefault();
      alert("請輸入遊戲暱稱");
      return;
    }
    localStorage.setItem("nickname", nickname);
    localStorage.setItem(
      "levels",
      JSON.stringify({
        level1: { isLocked: true },
        level2: { isLocked: true },
        level3: { isLocked: true },
        level4: { isLocked: true },
      })
    );
  };

  return (
    <>
      <Head>
        <title>Nickname</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.container_circle}>
          {/* decoration */}
          <div className={styles.stars}>
            <div className={styles.stars_sm}>
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
            </div>
            <Image src="/img_star_lg.svg" alt="star" width={50} height={50} />
            <div className={styles.stars_sm}>
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
              <Image src="/img_star_sm.svg" alt="star" width={18} height={18} />
            </div>
          </div>

          {/* input */}
          <div className={styles.input_wrapper}>
            <label htmlFor="nickname" className={styles.nickname_label}>
              取一個超酷的遊戲暱稱吧!
            </label>
            <input
              type="text"
              name="nickname"
              id="nickname"
              placeholder="請輸入遊戲暱稱"
              value={nickname}
              onChange={(e) => setNickname(e.target.value)}
            />
          </div>

          {/* checkbox */}
          <div className={styles.checkbox_wrapper}>
            <input type="checkbox" name="" id="toggleIsChecked" />
            您同意<span>使用者條款</span>與<span>隱私權政策</span>
          </div>

          {/* button */}
          <div className={styles.button_container}>
            <Link href="/intro1">
              <Button onClick={handleGoClick}>GO!</Button>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
