import { useRouter } from "next/router";
import Head from "next/head";
import levels from "../../data/levelsData";
import Success from "../../components/success";

export default function StagePage() {
  const router = useRouter();
  const { success } = router.query;

  // 查找對應的 stage
  const levelData = levels.find((level) => level.stage === Number(success));
  console.log(levelData);

  if (!levelData) {
    return <p>加載中...</p>;
  }

  return (
    <>
      <Head>
        <title>Level {levelData.stage}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Success level={levelData.stage} />
    </>
  );
}
